language: go

go:
  - "1.11"

before_deploy:
  - git config --local user.name "${GIT_USER_NAME}"
  - git config --local user.email "${GIT_USER_EMAIL}"
  - export TRAVIS_TAG="$TRAVIS_BRANCH-build-$(git log --format=%h -1)"
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: ghwebhooks
  skip_cleanup: true