name: CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Build Project
        run: make

      - name: Release Project
        if: contains(github.ref, 'master')
        uses: ksokol/github-release-action@master
        with:
          tag_name: ${{ github.ref }}-${{ github.sha }}
          release_name: ${{ github.sha }}
          asset_path: bin/ghwebhooks
          asset_name: ghwebhooks
          asset_content_type: application/octet-stream
